apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisCluster
metadata:
  name: redis-cluster
spec:
  clusterSize: 3
  persistenceEnabled: true
  kubernetesConfig:
    image: quay.io/opstree/redis:v7.0.15
    imagePullPolicy: IfNotPresent
  redisExporter:
    enabled: true
    image: quay.io/opstree/redis-exporter:v1.48.0
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: "local-storage"
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi